{% set version = "0.0.0" %}


package:
  name: lue
  version: {{ version }}


source:
  path: ../../


build:
  number: 0


requirements:
  build:
    # Section for the native build platform. Think "build-tools", that run on the native platform,
    # but output results for the target platform.
    # Dependencies required during the build phase not needed on the host.
    - python                                     # [build_platform != target_platform]
    - cross-python_{{ target_platform }}         # [build_platform != target_platform]
    - numpy >1.17                                # [build_platform != target_platform]
    - pybind11                                   # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - make                                       # [unix]
    - git
    - conan <2
    - cmake
    - ninja                                      # [not win]

  host:
    # Section for the target platform. Might not be the same as the build platform!
    # Dependencies required during build phase needed on the host.
    - python
    - numpy >1.17
    - boost-cpp
    - hdf5
    - hpx
    - libgdal
    - pybind11
    - fmt
    - docopt  # templatize.py
    - docopt.cpp
    - jinja2  # templatize.py
    - nlohmann_json

  run:
    # Dependencies required for using the software.
    # Stuff required when using LUE.
    - docopt  # lue.qa
    - docopt.cpp
    - fmt
    - hdf5
    - hpx
    - libgdal
    - matplotlib  # lue.qa
    - {{ pin_compatible('numpy') }}
    - python
    - python-dateutil  # lue.qa


test:
    commands:
       - lue_translate -h
       - lue_validate -h
       - lue_scalability -h                      # [not win]


about:
  home: https://lue.computationalgeography.org/
  license: MIT
  license_file: LICENSE.txt
  summary: LUE scientific database and environmental modelling framework.
  description: |
    LUE is software for storing and manipulating large amounts of information
    for large amounts of objects. This information can optionally have a
    reference in time and space. For example, LUE can represent collections of
    wandering animals and their properties, some of which are changing through
    time, or the elevation of the surface of one or multiple areas. The software
    is useful, and currently mainly used, in the context of environmental
    modelling of biological and physical systems, represented by agents and
    fields, but we make sure that the software is as generic as possible,
    allowing it to be useful in other contexts as well.

    Currently, LUE contains two main parts: *LUE data model* and *LUE
    framework*. LUE data model is an implementation of the LUE physical data
    model, which allows users to perform I/O to the "LUE Scientific Database".
    It allows for the storage of large amounts of objects and their location
    in time and space, and their properties.

    LUE framework is a collection of data types and algorithms that can be
    combined to translate large amounts of information. It allows computations
    to be performed on hardware ranging from laptops to compute clusters,
    without the user having to know about high-performance computing and
    the related technology.
  doc_url: https://lue.computationalgeography.org/doc/
  dev_url: https://github.com/computationalgeography/lue/


extra:
  recipe-maintainers:
    - kordejong
    - oliverschmitz
