{% set version = "0.3.10" %}


package:
  name: lue
  version: {{ version }}


source:
  path: ../../


build:
  number: 0
  skip: True                                     # [osx and x86_64]


requirements:
  build:
    - {{ compiler('cxx') }}
    - ninja
    - python                                     # [build_platform != target_platform]
    - cross-python_{{ target_platform }}         # [build_platform != target_platform]
    - numpy                                      # [build_platform != target_platform]

  host:
    - python
    - numpy
    - libboost-devel  # Only CMake scripts (BoostConfig.cmake, etc)
    - libboost-headers  # Only headers
    - hdf5
    - hpx
    - libgdal
    - pybind11
    - docopt  # templatize.py
    - jinja2  # templatize.py
    - nlohmann_json
    - cxxopts

  run:
    - docopt  # lue.qa
    - hdf5
    - hpx
    - libgdal
    - matplotlib-base  # lue.qa
    - {{ pin_compatible('numpy') }}
    - python
    - python-dateutil  # lue.qa


test:
  imports:
    - lue                                        # [not (osx and arm64)]
    - lue.data_model                             # [not (osx and arm64)]
    - lue.framework                              # [not (osx and arm64)]
    - lue.pcraster                               # [not (osx and arm64)]
    - lue.qa.scalability                         # [not (osx and arm64)]
  commands:
    - lue_translate -h                           # [not (osx and arm64)]
    - lue_validate -h                            # [not (osx and arm64)]
    - lue_calculate.py -h                        # [not (osx and arm64)]
    - lue_scalability.py -h                      # [not (osx and arm64)]


about:
  home: https://lue.computationalgeography.org/
  license: MIT
  license_file: LICENSE.txt
  summary: LUE scientific database and environmental modelling framework.
  description: |
    LUE is software supporting the representation and numerical simulation of geographical
    systems. Using LUE, model developers can develop models using a syntax that looks very
    similar to map algebra, in either Python or C++. Given such a model, modellers can simulate
    real-world geographical systems with a large extent and at high resolutions. LUE models
    can be executed on small laptops and on large cluster partitions.

    LUE is the result of multiple research projects performed by the Computational Geography
    group at Utrecht University in the Netherlands. One of the focus areas of this group is
    to improve on the concepts and design of numerical simulation frameworks for geographical
    systems, with respect to their functionality and performance.

    LUE supports both agent-based and field-based modelling of geographical systems, with the
    support for field-based modelling currently being the most mature.
  doc_url: https://lue.computationalgeography.org/doc/
  dev_url: https://github.com/computationalgeography/lue/


extra:
  recipe-maintainers:
    - kordejong
    - oliverschmitz
