#pragma once
#include "lue/framework/algorithm/arithmetic.hpp"
#include "lue/framework/algorithm/comparison.hpp"
#include "lue/framework/algorithm/focal.hpp"
#include "lue/framework/algorithm/logical.hpp"

#include "lue/framework/algorithm/all.hpp"
#include "lue/framework/algorithm/any.hpp"
#include "lue/framework/algorithm/none.hpp"
#include "lue/framework/algorithm/sum.hpp"

#include "lue/framework/algorithm/trigonometric.hpp"

#include "lue/framework/algorithm/pow.hpp"
#include "lue/framework/algorithm/sqrt.hpp"

#include "lue/framework/algorithm/array_like.hpp"
#include "lue/framework/algorithm/array_partition_id.hpp"
#include "lue/framework/algorithm/cast.hpp"
#include "lue/framework/algorithm/convolve.hpp"
#include "lue/framework/algorithm/copy.hpp"
#include "lue/framework/algorithm/empty.hpp"
#include "lue/framework/algorithm/fill.hpp"
#include "lue/framework/algorithm/iterate_per_element.hpp"
#include "lue/framework/algorithm/locality_id.hpp"
#include "lue/framework/algorithm/mesh_grid.hpp"
#include "lue/framework/algorithm/range.hpp"
#include "lue/framework/algorithm/uniform.hpp"
#include "lue/framework/algorithm/unique.hpp"
#include "lue/framework/algorithm/unique_id.hpp"
#include "lue/framework/algorithm/where.hpp"
