include(CMakeFindDependencyMacro)
find_dependency(Boost
    COMPONENTS
        filesystem
)
find_dependency(HDF5
    COMPONENTS
        C
)
if(HDF5_IS_PARALLEL)
    find_dependency(MPI)
endif()
include("${CMAKE_CURRENT_LIST_DIR}/lue_targets.cmake")
