name: Linux Conda package

on:
  push:
    branches-ignore:
      - ghxyz
    paths:
      - ".github/workflows/linux-conda.yml"
      - "source/**"
      - "!source/qa/python/qa/**"
      - "environment/cmake/**"
      - "environment/conda/build.sh"
      - "environment/conda/meta.yaml"
      - "environment/conda/run_test.py"

jobs:
    build:

        strategy:
            matrix:
                os: ["ubuntu-22.04"]
                python-version: ["3.9"]
            fail-fast: false

        runs-on: ${{ matrix.os }}

        name: ${{ matrix.os }} - ${{ matrix.python-version }}

        steps:

        - name: Configure system
          run: |
              sudo apt-get update
              sudo apt install mesa-common-dev libglu1-mesa-dev libgl1-mesa-glx

        - name: Checkout LUE
          uses: actions/checkout@v3

        - uses: conda-incubator/setup-miniconda@v2
          with:
              auto-update-conda: true
              python-version: ${{ matrix.python-version }}
              channels: conda-forge

        - shell: bash -l {0}
          run: |
              conda install boa

        - name: Build
          shell: bash -l {0}
          run: |
              conda mambabuild environment/conda  # --channel conda-forge --override-channels
