name: Linux Conda package

on: [push]

jobs:
    build:

        strategy:
            matrix:
                os: ["ubuntu-latest"]
                python-version: [3.8]

        runs-on: ${{ matrix.os }}

        name: ${{ matrix.os }} - ${{ matrix.python-version }}

        steps:

        - name: checkout lue
          uses: actions/checkout@v2

        - name: configure system
          run: |
              sudo apt update
              sudo apt autoremove
              sudo apt upgrade
        - uses: conda-incubator/setup-miniconda@v2
          with:
              auto-update-conda: true
              python-version: ${{ matrix.python-version }}
              channels: conda-forge
